import { FileText } from 'lucide-react'
import TemporalFullReport from '@/components/TemporalFullReport'

export default function TemporalFullReportPage() {
  return (
    <div className="mx-auto max-w-[1800px] px-6 py-8">
      <div className="flex items-center gap-2 mb-1 text-xs tracking-wider uppercase text-muted-foreground">
        <FileText size={12} /> ApexFi / Temporal Validation / Full Report
      </div>
      <h1 className="text-2xl font-semibold font-display">Complete Baseline Evaluation Report</h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Every real, measured result from the temporal research thread — threshold optimization,
        explainability, hybrid model comparison, feature ablation, and database performance. All
        figures below are read directly from real, saved results generated by the actual training
        and benchmarking scripts, not estimated or simulated.
      </p>

      <div className="mt-6">
        <TemporalFullReport />
      </div>
    </div>
  )
}