// Real, verified Gold-layer stats (from Stage 1 completion) — not invented
// mock numbers. Once /api/datasets/ is wired in, this file becomes the
// loading-state fallback rather than the source of truth.

export const mockDatasetList = [
  {
    id: 'ieee_cis_features',
    name: 'IEEE-CIS Transactions',
    description: 'Card transaction features — device, card, and behavioral signals.',
    category: 'Tabular',
    source: 'Kaggle',
    rows: 590540,
    columns: 440,
    status: 'Loaded',
  },
  {
    id: 'ieee_cis_transaction_edges',
    name: 'IEEE-CIS Transaction Graph',
    description: 'Derived edges: device_shared and card_shared, built from evidence (fraud lift).',
    category: 'Graph',
    source: 'Derived',
    rows: 17322878,
    columns: 3,
    status: 'Loaded',
  },
  {
    id: 'dgraph_fin_nodes',
    name: 'DGraph-Fin Users',
    description: 'Finvolution user network nodes — 17 features, fraud/normal/background labels.',
    category: 'Graph',
    source: 'dgraph.xinye.com',
    rows: 3700550,
    columns: 24,
    status: 'Loaded',
  },
  {
    id: 'dgraph_fin_edges',
    name: 'DGraph-Fin Connections',
    description: 'Emergency-contact relationships between users, with timestamps.',
    category: 'Graph',
    source: 'dgraph.xinye.com',
    rows: 4300999,
    columns: 5,
    status: 'Loaded',
  },
  {
    id: 'rbi_money_rates',
    name: 'RBI Money Rates',
    description: 'Bank rate, SBI lending rate, call money rate — fiscal years 2000-01 to 2017-18.',
    category: 'Tabular',
    source: 'data.gov.in (RBI)',
    rows: 18,
    columns: 7,
    status: 'Loaded',
  },
  {
    id: 'npci_digital_payments_quarterly',
    name: 'NPCI Digital Payments (Quarterly)',
    description: 'Real digital-payment volume and value, 2022, by quarter.',
    category: 'Tabular',
    source: 'data.gov.in (NPCI)',
    rows: 4,
    columns: 3,
    status: 'Loaded',
  },
  {
    id: 'npci_digital_payments_monthly',
    name: 'NPCI Digital Payments (Monthly)',
    description: 'Real digital-payment volume and value, by month.',
    category: 'Tabular',
    source: 'data.gov.in (NPCI)',
    rows: 12,
    columns: 3,
    status: 'Loaded',
  },
]
