// Every answer/supporting figure here traces to a real, verified finding
// from the pipeline. Translations into Tamil, Kannada, Telugu, and
// Malayalam are machine-generated by Claude for this demo — they have NOT
// been reviewed by a native speaker. Verify accuracy before using in any
// live or graded presentation, especially the technical/statistical terms.

export const LANGUAGES = [
  { code: 'en-IN', label: 'English' },
  { code: 'ta-IN', label: 'Tamil' },
  { code: 'kn-IN', label: 'Kannada' },
  { code: 'te-IN', label: 'Telugu' },
  { code: 'ml-IN', label: 'Malayalam' },
]

export const suggestedQuestions = [
  {
    question: 'What is the overall fraud rate in the IEEE-CIS dataset?',
    answer:
      'The overall fraud rate is 3.499%, with 20,663 transactions flagged as fraud out of 590,540 total transactions.',
    supportingData: [
      { label: 'Total transactions', value: '590,540' },
      { label: 'Fraud count', value: '20,663' },
      { label: 'Fraud rate', value: '3.499%' },
    ],
    source: 'gold.ieee_cis_features',
    translations: {
      'ta-IN': {
        question: 'IEEE-CIS தரவுத்தொகுப்பில் ஒட்டுமொத்த மோசடி விகிதம் என்ன?',
        answer:
          'ஒட்டுமொத்த மோசடி விகிதம் 3.499% ஆகும், மொத்தம் 590,540 பரிவர்த்தனைகளில் 20,663 பரிவர்த்தனைகள் மோசடியாகக் குறிக்கப்பட்டுள்ளன.',
      },
      'kn-IN': {
        question: 'IEEE-CIS ಡೇಟಾಸೆಟ್‌ನಲ್ಲಿ ಒಟ್ಟಾರೆ ವಂಚನೆ ದರ ಎಷ್ಟು?',
        answer:
          'ಒಟ್ಟಾರೆ ವಂಚನೆ ದರ 3.499%, ಒಟ್ಟು 590,540 ವಹಿವಾಟುಗಳಲ್ಲಿ 20,663 ವಹಿವಾಟುಗಳನ್ನು ವಂಚನೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.',
      },
      'te-IN': {
        question: 'IEEE-CIS డేటాసెట్‌లో మొత్తం మోసం రేటు ఎంత?',
        answer:
          'మొత్తం మోసం రేటు 3.499%, మొత్తం 590,540 లావాదేవీలలో 20,663 లావాదేవీలు మోసంగా గుర్తించబడ్డాయి.',
      },
      'ml-IN': {
        question: 'IEEE-CIS ഡാറ്റാസെറ്റിലെ മൊത്തം വഞ്ചന നിരക്ക് എത്രയാണ്?',
        answer:
          'മൊത്തം വഞ്ചന നിരക്ക് 3.499% ആണ്, ആകെ 590,540 ഇടപാടുകളിൽ 20,663 ഇടപാടുകൾ വഞ്ചനയായി അടയാളപ്പെടുത്തിയിട്ടുണ്ട്.',
      },
    },
  },
  {
    question: 'How many users and connections are in DGraph-Fin?',
    answer:
      'DGraph-Fin contains 3,700,550 user nodes and 4,300,999 connections in its emergency-contact network.',
    supportingData: [
      { label: 'User nodes', value: '3,700,550' },
      { label: 'Connections', value: '4,300,999' },
    ],
    source: 'gold.dgraph_fin_nodes, gold.dgraph_fin_edges',
    translations: {
      'ta-IN': {
        question: 'DGraph-Fin இல் எத்தனை பயனர்களும் இணைப்புகளும் உள்ளன?',
        answer:
          'DGraph-Fin இல் 3,700,550 பயனர் நோட்களும், அவசரகால தொடர்பு வலையமைப்பில் 4,300,999 இணைப்புகளும் உள்ளன.',
      },
      'kn-IN': {
        question: 'DGraph-Fin ನಲ್ಲಿ ಎಷ್ಟು ಬಳಕೆದಾರರು ಮತ್ತು ಸಂಪರ್ಕಗಳಿವೆ?',
        answer:
          'DGraph-Fin ನಲ್ಲಿ 3,700,550 ಬಳಕೆದಾರ ನೋಡ್‌ಗಳು ಮತ್ತು ತುರ್ತು ಸಂಪರ್ಕ ಜಾಲದಲ್ಲಿ 4,300,999 ಸಂಪರ್ಕಗಳಿವೆ.',
      },
      'te-IN': {
        question: 'DGraph-Fin లో ఎంతమంది వినియోగదారులు మరియు కనెక్షన్‌లు ఉన్నాయి?',
        answer:
          'DGraph-Fin లో 3,700,550 వినియోగదారు నోడ్‌లు మరియు అత్యవసర సంప్రదింపు నెట్‌వర్క్‌లో 4,300,999 కనెక్షన్‌లు ఉన్నాయి.',
      },
      'ml-IN': {
        question: 'DGraph-Fin ൽ എത്ര ഉപയോക്താക്കളും കണക്ഷനുകളും ഉണ്ട്?',
        answer:
          'DGraph-Fin ൽ 3,700,550 ഉപയോക്തൃ നോഡുകളും, അടിയന്തര ബന്ധ ശൃംഖലയിൽ 4,300,999 കണക്ഷനുകളും ഉണ്ട്.',
      },
    },
  },
  {
    question: 'What was the RBI bank rate in fiscal year 2017-18?',
    answer: 'The RBI bank rate in fiscal year 2017-18 was 6.25%, per real data.gov.in records.',
    supportingData: [
      { label: 'Fiscal year', value: '2017-18' },
      { label: 'Bank rate', value: '6.25%' },
    ],
    source: 'gold.rbi_money_rates',
    translations: {
      'ta-IN': {
        question: '2017-18 நிதியாண்டில் RBI வங்கி வட்டி விகிதம் என்ன?',
        answer:
          '2017-18 நிதியாண்டில் RBI வங்கி வட்டி விகிதம் 6.25% ஆக இருந்தது, இது data.gov.in இன் உண்மையான தரவுகளின் அடிப்படையில் உள்ளது.',
      },
      'kn-IN': {
        question: '2017-18 ಹಣಕಾಸು ವರ್ಷದಲ್ಲಿ RBI ಬ್ಯಾಂಕ್ ದರ ಎಷ್ಟಿತ್ತು?',
        answer:
          '2017-18 ಹಣಕಾಸು ವರ್ಷದಲ್ಲಿ RBI ಬ್ಯಾಂಕ್ ದರ 6.25% ಆಗಿತ್ತು, ಇದು data.gov.in ನ ನೈಜ ದಾಖಲೆಗಳ ಪ್ರಕಾರ.',
      },
      'te-IN': {
        question: '2017-18 ఆర్థిక సంవత్సరంలో RBI బ్యాంక్ రేటు ఎంత?',
        answer: '2017-18 ఆర్థిక సంవత్సరంలో RBI బ్యాంక్ రేటు 6.25%, ఇది data.gov.in నిజమైన రికార్డుల ప్రకారం.',
      },
      'ml-IN': {
        question: '2017-18 സാമ്പത്തിക വർഷത്തിൽ RBI ബാങ്ക് നിരക്ക് എത്രയായിരുന്നു?',
        answer:
          '2017-18 സാമ്പത്തിക വർഷത്തിൽ RBI ബാങ്ക് നിരക്ക് 6.25% ആയിരുന്നു, ഇത് data.gov.in ന്റെ യഥാർത്ഥ രേഖകൾ പ്രകാരമാണ്.',
      },
    },
  },
  {
    question: 'Which graph edge type shows the strongest fraud signal?',
    answer:
      'device_shared edges show the strongest signal — a fraud lift of 2.67x, compared to 0.82x for card_shared edges.',
    supportingData: [
      { label: 'device_shared lift', value: '2.67x' },
      { label: 'card_shared lift', value: '0.82x' },
    ],
    source: 'gold.ieee_cis_transaction_edges',
    translations: {
      'ta-IN': {
        question: 'எந்த வகை இணைப்பு (edge) மிகவும் வலுவான மோசடி சமிக்ஞையைக் காட்டுகிறது?',
        answer:
          'device_shared இணைப்புகள் மிகவும் வலுவான சமிக்ஞையைக் காட்டுகின்றன — 2.67 மடங்கு மோசடி அதிகரிப்பு, card_shared இணைப்புகளுக்கு இது 0.82 மடங்கு மட்டுமே.',
      },
      'kn-IN': {
        question: 'ಯಾವ ಗ್ರಾಫ್ ಎಡ್ಜ್ ಪ್ರಕಾರವು ಬಲವಾದ ವಂಚನೆ ಸಂಕೇತವನ್ನು ತೋರಿಸುತ್ತದೆ?',
        answer:
          'device_shared ಎಡ್ಜ್‌ಗಳು ಬಲವಾದ ಸಂಕೇತವನ್ನು ತೋರಿಸುತ್ತವೆ — 2.67 ಪಟ್ಟು ವಂಚನೆ ಏರಿಕೆ, card_shared ಎಡ್ಜ್‌ಗಳಿಗೆ ಇದು 0.82 ಪಟ್ಟು ಮಾತ್ರ.',
      },
      'te-IN': {
        question: 'ఏ గ్రాఫ్ ఎడ్జ్ రకం బలమైన మోసం సంకేతాన్ని చూపిస్తుంది?',
        answer:
          'device_shared ఎడ్జ్‌లు బలమైన సంకేతాన్ని చూపిస్తాయి — 2.67 రెట్లు మోసం పెరుగుదల, card_shared ఎడ్జ్‌లకు ఇది 0.82 రెట్లు మాత్రమే.',
      },
      'ml-IN': {
        question: 'ഏത് ഗ്രാഫ് എഡ്ജ് തരമാണ് ഏറ്റവും ശക്തമായ വഞ്ചന സൂചന കാണിക്കുന്നത്?',
        answer:
          'device_shared എഡ്ജുകൾ ഏറ്റവും ശക്തമായ സൂചന കാണിക്കുന്നു — 2.67 മടങ്ങ് വഞ്ചന വർദ്ധനവ്, card_shared എഡ്ജുകൾക്ക് ഇത് 0.82 മടങ്ങ് മാത്രമാണ്.',
      },
    },
  },
  {
    question: 'Do fraud users have more or fewer connections than normal users?',
    answer:
      'Fraud users show measurably fewer connections (avg. 1.95) than normal users (avg. 2.89) in the DGraph-Fin emergency-contact network.',
    supportingData: [
      { label: 'Normal avg. degree', value: '2.89' },
      { label: 'Fraud avg. degree', value: '1.95' },
    ],
    source: 'gold.dgraph_fin_nodes',
    translations: {
      'ta-IN': {
        question: 'மோசடி பயனர்களுக்கு சாதாரண பயனர்களை விட அதிக இணைப்புகள் உள்ளனவா அல்லது குறைவா?',
        answer:
          'மோசடி பயனர்கள் சராசரியாக 1.95 இணைப்புகளையும், சாதாரண பயனர்கள் 2.89 இணைப்புகளையும் கொண்டுள்ளனர் — இது DGraph-Fin அவசரகால தொடர்பு வலையமைப்பில் காணப்படுகிறது.',
      },
      'kn-IN': {
        question: 'ವಂಚನೆ ಬಳಕೆದಾರರಿಗೆ ಸಾಮಾನ್ಯ ಬಳಕೆದಾರರಿಗಿಂತ ಹೆಚ್ಚು ಅಥವಾ ಕಡಿಮೆ ಸಂಪರ್ಕಗಳಿವೆಯೇ?',
        answer:
          'ವಂಚನೆ ಬಳಕೆದಾರರು ಸರಾಸರಿ 1.95 ಸಂಪರ್ಕಗಳನ್ನು ಹೊಂದಿದ್ದಾರೆ, ಸಾಮಾನ್ಯ ಬಳಕೆದಾರರು 2.89 ಸಂಪರ್ಕಗಳನ್ನು ಹೊಂದಿದ್ದಾರೆ — ಇದು DGraph-Fin ತುರ್ತು ಸಂಪರ್ಕ ಜಾಲದಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ.',
      },
      'te-IN': {
        question: 'మోసం చేసే వినియోగదారులకు సాధారణ వినియోగదారుల కంటే ఎక్కువ లేదా తక్కువ కనెక్షన్‌లు ఉన్నాయా?',
        answer:
          'మోసం చేసే వినియోగదారులు సగటున 1.95 కనెక్షన్‌లు కలిగి ఉన్నారు, సాధారణ వినియోగదారులు 2.89 కనెక్షన్‌లు కలిగి ఉన్నారు — ఇది DGraph-Fin అత్యవసర సంప్రదింపు నెట్‌వర్క్‌లో కనిపిస్తుంది.',
      },
      'ml-IN': {
        question: 'വഞ്ചന ഉപയോക്താക്കൾക്ക് സാധാരണ ഉപയോക്താക്കളേക്കാൾ കൂടുതൽ അതോ കുറവോ കണക്ഷനുകൾ ഉണ്ട്?',
        answer:
          'വഞ്ചന ഉപയോക്താക്കൾക്ക് ശരാശരി 1.95 കണക്ഷനുകളും, സാധാരണ ഉപയോക്താക്കൾക്ക് 2.89 കണക്ഷനുകളും ഉണ്ട് — ഇത് DGraph-Fin അടിയന്തര ബന്ധ ശൃംഖലയിൽ കാണപ്പെടുന്നു.',
      },
    },
  },
]

const FALLBACK_BY_LANG = {
  'en-IN':
    "This question isn't in the mock demo set yet. This demo isn't connected to a live database — only the 5 suggested questions have real pre-set answers. Once the text-to-SQL backend is wired up, this would generate a real SQL query against the Gold layer.",
  'ta-IN':
    'இந்தக் கேள்வி இன்னும் மாதிரி தொகுப்பில் இல்லை. இந்த டெமோ நேரடி தரவுத்தளத்துடன் இணைக்கப்படவில்லை — 5 பரிந்துரைக்கப்பட்ட கேள்விகளுக்கு மட்டுமே உண்மையான பதில்கள் உள்ளன.',
  'kn-IN':
    'ಈ ಪ್ರಶ್ನೆ ಇನ್ನೂ ಮಾದರಿ ಸೆಟ್‌ನಲ್ಲಿ ಇಲ್ಲ. ಈ ಡೆಮೊ ನೇರ ಡೇಟಾಬೇಸ್‌ಗೆ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ — ಸೂಚಿಸಲಾದ 5 ಪ್ರಶ್ನೆಗಳಿಗೆ ಮಾತ್ರ ನೈಜ ಉತ್ತರಗಳಿವೆ.',
  'te-IN':
    'ఈ ప్రశ్న ఇంకా మాదిరి సెట్‌లో లేదు. ఈ డెమో ప్రత్యక్ష డేటాబేస్‌కు అనుసంధానించబడలేదు — సూచించిన 5 ప్రశ్నలకు మాత్రమే నిజమైన సమాధానాలు ఉన్నాయి.',
  'ml-IN':
    'ഈ ചോദ്യം ഇതുവരെ മാതൃകാ സെറ്റിൽ ഇല്ല. ഈ ഡെമോ തത്സമയ ഡാറ്റാബേസുമായി ബന്ധിപ്പിച്ചിട്ടില്ല — നിർദ്ദേശിച്ച 5 ചോദ്യങ്ങൾക്ക് മാത്രമേ യഥാർത്ഥ ഉത്തരങ്ങൾ ഉള്ളൂ.',
}

export function findAnswer(query, lang = 'en-IN') {
  const q = query.toLowerCase()
  const match = suggestedQuestions.find((sq) => {
    if (sq.question.toLowerCase() === q) return true
    const t = sq.translations[lang]
    return t && t.question.toLowerCase() === q
  })

  if (match) {
    const localized = lang === 'en-IN' ? match : match.translations[lang] || match
    return {
      question: localized.question,
      answer: localized.answer,
      answerEnglish: match.answer, // always spoken aloud in English — regional TTS voices are unreliable
      supportingData: match.supportingData,
      source: match.source,
      isFallback: false,
    }
  }

  return {
    question: query,
    answer: FALLBACK_BY_LANG[lang] || FALLBACK_BY_LANG['en-IN'],
    answerEnglish: FALLBACK_BY_LANG['en-IN'],
    supportingData: [],
    source: null,
    isFallback: true,
  }
}

// English list is what's shown as clickable suggestion chips (keeps the UI
// simple); once a language is selected, typing/speaking the translated
// version of any of these 5 also matches correctly (see findAnswer above).
export { suggestedQuestions as default }
